# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'KituraTeamSchedule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KituraTeamSchedule
pod 'KituraKit', :git => 'https://github.com/IBM-Swift/KituraKit.git', :branch => 'pod'


end
